apiVersion: v1
kind: ConfigMap
metadata:
  name: patroni-config
data:
  PATRONI_SCOPE: "demo"
  PATRONI_ETCD_HOSTS: "'etcd-0.etcd:2379','etcd-1.etcd:2379','etcd-2.etcd:2379'"
  PATRONI_RESTAPI_USERNAME: "admin"
  PATRONI_RESTAPI_PASSWORD: "admin"
  ETCDCTL_ENDPOINTS: "http://etcd-0.etcd:2379,http://etcd-1.etcd:2379,http://etcd-2.etcd:2379"
  PATRONI_SUPERUSER_USERNAME: "postgres"
  PATRONI_SUPERUSER_PASSWORD: "postgres"
  PATRONI_REPLICATION_USERNAME: "replicator"
  PATRONI_REPLICATION_PASSWORD: "replicate"
  PATRONI_admin_PASSWORD: "admin"
  PATRONI_admin_OPTIONS: "createdb,createrole"