apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
spec:
  serviceName: "etcd"
  replicas: 3
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: pioula/patronit:1
        command: ["/bin/sh", "-c"]
        args: ["source /etc/patroni/patroni.env && etcd"]
        ports:
        - containerPort: 2379
        - containerPort: 2380
        envFrom:
        - configMapRef:
            name: etcd-config
        env:
        - name: ETCD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: ETCD_INITIAL_ADVERTISE_PEER_URLS
          value: "http://$(ETCD_NAME).etcd:2380"