apiVersion: v1
data:
  rootHost: JQ==
  rootPassword: c2FraWxh
  rootUser: cm9vdA==
kind: Secret
metadata:
  creationTimestamp: null
  name: mypwds
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
spec:
  secretName: mypwds
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1