apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka-cluster
  ports:
  - port: 9092
    targetPort: 9092
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-controller-headless
spec:
  ports:
  - port: 9092
    targetPort: 9092
  clusterIP: None
  selector:
    app: kafka-cluster
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-controller
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-cluster
  serviceName: "kafka-controller-headless"
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:2.6.0  
        securityContext:
          runAsUser: 0
        resources:
          requests:
            memory: "1G"
            cpu: "1"             
        ports:
        - containerPort: 9092
        command:
        - sh
        - -c
        - |
          export KAFKA_CFG_ADVERTISED_LISTENERS="PLAINTEXT://${HOSTNAME}.kafka-controller-headless.${POD_NAMESPACE}.svc.cluster.local:9092"
          exec /entrypoint.sh /run.sh
        env:
        - name: KAFKA_CFG_ZOOKEEPER_CONNECT
          value: crs-zookeeper-0.zookeeper-cluster.parser.svc.cluster.local:2181,crs-zookeeper-1.zookeeper-cluster.parser.svc.cluster.local:2181,crs-zookeeper-2.zookeeper-cluster.parser.svc.cluster.local:2181
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace