- name: Create K8S resources
  hosts: ansible
  tasks:
  - name: Create Parser Namespace
    kubernetes.core.k8s:
      src: ~/k8s-manifests/namespace/namespace.yml
      wait: yes
      wait_timeout: 300  

  - name: Set default namespace to parser
    shell: kubectl config set-context --current --namespace=parser

  - name: Deploy local-path
    shell: kubectl apply -f ~/k8s-manifests/local-path/local-path.yml

  - name: Deploy redis config map
    kubernetes.core.k8s:
      src: ~/k8s-manifests/redis/cm.yml
      wait: yes
      wait_timeout: 300    

  - name: Deploy redis
    kubernetes.core.k8s:
      src: ~/k8s-manifests/redis/redis-cluster.yml
      wait: yes
      wait_timeout: 300
      
  - ansible.builtin.shell: "bash ~/k8s-manifests/redis/redis.sh"
    register: redis_setup_result
    changed_when: redis_setup_result.rc == 0
    failed_when: redis_setup_result.rc != 0
    environment:
      KUBECONFIG: "{{ ansible_env.HOME }}/.kube/config"
    
  - name: Display Redis setup script output
    ansible.builtin.debug:
      var: redis_setup_result.stdout_lines
