- name: Configure Join Commands on Master Node
  hosts: master
  become: yes
  tasks:
    - name: Retrieve Join Command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set Join Command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join Worker Nodes
  hosts: workers
  become: yes
  tasks:
    - name: Enable TCP port 6443 (On Master) is able to connect from Worker
      wait_for:
        host: st115vm102.rtb-lab.pl
        port: 6443
        timeout: 30

    - name: Join worker to cluster
      shell: "{{ hostvars['st115@st115vm102.rtb-lab.pl'].join_command }} >> node_joined.log"
      args:
        chdir: /home/st115
        creates: node_joined.log