apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: case3
  name: case3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: case3
  template:
    metadata:
      labels:
        app: case3
    spec:
      initContainers:
      - name: init-db
        image: mysql:8.0
        command: ['sh', '-c', 'mysql -h mysql-cluster -uroot -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS allezondb;"']
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mypwds
              key: rootPassword
      containers:
      - image: pioula/case3:28
        name: case3
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mypwds
              key: rootPassword
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: mypwds
              key: rootUser
        - name: MYSQL_ROOT_HOST
          valueFrom:
            secretKeyRef:
              name: mypwds
              key: rootHost
        - name: MYSQL_HOST
          value: "mysql-cluster"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "allezondb"
        - name: MYSQL_TABLE
          value: "user_tag_aggregations"
        - name: KAFKA_TOPIC
          value: "usertagevents"
        - name: KAFKA_APP_ID
          value: "user-tag-aggregator"
        - name: KAFKA_BOOTSTRAP
          value: "kafka:9092"
        resources: {}