apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-0  # Replace with each of your PVC names
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage